/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KenyanRouteImport } from './routes/kenyan'
import { Route as IndexRouteImport } from './routes/index'

const KenyanRoute = KenyanRouteImport.update({
  id: '/kenyan',
  path: '/kenyan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kenyan': typeof KenyanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kenyan': typeof KenyanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kenyan': typeof KenyanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kenyan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kenyan'
  id: '__root__' | '/' | '/kenyan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KenyanRoute: typeof KenyanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kenyan': {
      id: '/kenyan'
      path: '/kenyan'
      fullPath: '/kenyan'
      preLoaderRoute: typeof KenyanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KenyanRoute: KenyanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
