<#
.SYNOPSIS
    Safe development reset for ArbScanner on Windows.

.DESCRIPTION
    Stops ONLY this project's own API/frontend/engine processes,
    clears disposable runtime/cache state (including in-memory
    credential health state), then restarts the application and
    reports whether it came back up.

    Project processes are identified by inspecting each running
    python.exe / node.exe process's command line for BOTH this
    project's own path AND a known ArbScanner entrypoint marker
    (uvicorn/api:app, run_engine.py, vite/npm). This never matches
    unrelated python/node processes elsewhere on the machine.

    Never touches: source code, .venv, node_modules, config templates
    (.env, .env.example, credentials.example.json), credentials.json
    (the encrypted secret store), or *.log files (unless -ClearLogs is
    passed explicitly).

.PARAMETER DryRun
    Print the actions that would be taken without performing any of
    them (no processes stopped/started, nothing deleted).

.PARAMETER SkipRestart
    Stop and clean up, but do not start the application again.

.PARAMETER ClearLogs
    Also delete *.log files. Logs are preserved by default.

.EXAMPLE
    .\scripts\reset-dev.ps1 -DryRun
    .\scripts\reset-dev.ps1
    .\scripts\reset-dev.ps1 -SkipRestart
#>
param(
    [switch]$DryRun,
    [switch]$SkipRestart,
    [switch]$ClearLogs
)

$ErrorActionPreference = "Stop"
$ProjectRoot = Split-Path -Parent $PSScriptRoot
Set-Location $ProjectRoot

function Write-Status {
    param([string]$Message)
    Write-Host "[reset-dev] $Message"
}

function Get-ProjectProcesses {
    <#
    Returns python.exe / node.exe processes whose command line
    references BOTH this project's path AND a known ArbScanner
    entrypoint. Deliberately conservative: processes that only match
    one condition (e.g. some other python.exe that happens to be
    running from an unrelated directory) are never included.
    #>
    $escapedRoot = [regex]::Escape($ProjectRoot)
    $markers = @("uvicorn", "api:app", "run_engine.py", "vite", "npm")

    Get-CimInstance Win32_Process -Filter "Name='python.exe' OR Name='node.exe'" |
        Where-Object {
            $proc = $_

            if (-not $proc.CommandLine) {
                return $false
            }

            if ($proc.CommandLine -notmatch $escapedRoot) {
                return $false
            }

            $matched = $false
            foreach ($marker in $markers) {
                if ($proc.CommandLine -match [regex]::Escape($marker)) {
                    $matched = $true
                    break
                }
            }

            return $matched
        }
}

Write-Status "Project root: $ProjectRoot"

if ($DryRun) {
    Write-Status "DRY RUN -- no processes will be stopped/started and no files will be modified."
}

# ---------------------------------------------------------------------
# 1. Stop this project's own processes (API, frontend, engine).
# ---------------------------------------------------------------------
$targets = @(Get-ProjectProcesses)

if ($targets.Count -gt 0) {
    foreach ($proc in $targets) {
        $desc = "$($proc.Name) (PID $($proc.ProcessId))"

        if ($DryRun) {
            Write-Status "[DryRun] Would stop $desc"
        } else {
            Write-Status "Stopping $desc"
            try {
                Stop-Process -Id $proc.ProcessId -Force -ErrorAction Stop
            } catch {
                Write-Status "  Could not stop PID $($proc.ProcessId): $($_.Exception.Message)"
            }
        }
    }

    if (-not $DryRun) {
        Start-Sleep -Seconds 2
    }
} else {
    Write-Status "No running ArbScanner processes found."
}

# ---------------------------------------------------------------------
# 2. Clear disposable runtime/cache state.
#
#    Explicitly NEVER included here: source code, .venv, node_modules,
#    .env / .env.example / credentials.example.json, credentials.json.
# ---------------------------------------------------------------------
$disposablePaths = @(
    "runtime\credentials_state.json",  # in-memory credential health state
    "cached_opportunities.json",       # regenerated by the engine on next run
    "cached_status.json",              # regenerated by the engine on next tick
    "cached_status.json.tmp",
    "cached_opportunities.json.tmp",
    "output"                           # diagnostic snapshots, safe to clear
)

foreach ($relativePath in $disposablePaths) {
    $fullPath = Join-Path $ProjectRoot $relativePath

    if (Test-Path $fullPath) {
        if ($DryRun) {
            Write-Status "[DryRun] Would clear $relativePath"
        } else {
            Write-Status "Clearing $relativePath"
            Remove-Item -Path $fullPath -Recurse -Force -ErrorAction SilentlyContinue
        }
    }
}

if ($ClearLogs) {
    $logFiles = Get-ChildItem -Path $ProjectRoot -Filter "*.log" -Recurse -ErrorAction SilentlyContinue

    foreach ($log in $logFiles) {
        if ($DryRun) {
            Write-Status "[DryRun] Would delete log $($log.FullName)"
        } else {
            Write-Status "Deleting log $($log.FullName)"
            Remove-Item $log.FullName -Force -ErrorAction SilentlyContinue
        }
    }
}

# ---------------------------------------------------------------------
# 3. Reset in-memory/persisted credential health state explicitly.
#    (Belt-and-suspenders with step 2 above; never touches
#    credentials.json, the encrypted secrets.)
# ---------------------------------------------------------------------
$pythonExe = Join-Path $ProjectRoot ".venv\Scripts\python.exe"

if ($DryRun) {
    Write-Status "[DryRun] Would run: $pythonExe -m credentials.cli reset-state"
} elseif (Test-Path $pythonExe) {
    & $pythonExe -m credentials.cli reset-state
}

if ($SkipRestart) {
    Write-Status "SkipRestart set -- not restarting the application."
    exit 0
}

# ---------------------------------------------------------------------
# 4. Restart the application.
# ---------------------------------------------------------------------
if ($DryRun) {
    Write-Status "[DryRun] Would start: python -m uvicorn api:app --host 0.0.0.0 --port 8000"
    Write-Status "[DryRun] Would start: npm run dev (frontend)"
    Write-Status "[DryRun] Would start: python -u run_engine.py"
    Write-Status "Dry run complete -- no changes were made."
    exit 0
}

Write-Status "Starting API server..."
Start-Process -FilePath $pythonExe `
    -ArgumentList "-m", "uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000" `
    -WorkingDirectory $ProjectRoot -WindowStyle Minimized

Write-Status "Starting frontend dev server..."
Start-Process -FilePath "npm.cmd" `
    -ArgumentList "run", "dev" `
    -WorkingDirectory (Join-Path $ProjectRoot "frontend") -WindowStyle Minimized

Write-Status "Starting arbitrage engine..."
Start-Process -FilePath $pythonExe `
    -ArgumentList "-u", "run_engine.py" `
    -WorkingDirectory $ProjectRoot -WindowStyle Minimized

Start-Sleep -Seconds 5

# ---------------------------------------------------------------------
# 5. Health checks + report.
# ---------------------------------------------------------------------
Write-Status "Credential health check (provider=zenrows):"
& $pythonExe -m credentials.cli health --provider zenrows

$apiUp = $false
try {
    $response = Invoke-WebRequest -Uri "http://localhost:8000/opportunities" -TimeoutSec 5 -UseBasicParsing
    $apiUp = $response.StatusCode -eq 200
} catch {
    $apiUp = $false
}

if ($apiUp) {
    Write-Status "RESULT: API responded on port 8000. Restart succeeded."
} else {
    Write-Status "RESULT: API did not respond within the check window -- it may still be starting. Check its window for details."
}
